// GENERATED by tools/icons.py --emit — do not hand-edit.
// One semantic slot per row; all four clients use the SAME lucide id.
package com.agent.app.ui

import androidx.compose.ui.graphics.vector.ImageVector
import com.composables.icons.lucide.Lucide
import com.composables.icons.lucide.Plus
import com.composables.icons.lucide.LayoutGrid
import com.composables.icons.lucide.ArrowUp
import com.composables.icons.lucide.Asterisk
import com.composables.icons.lucide.Paperclip
import com.composables.icons.lucide.AudioLines
import com.composables.icons.lucide.ArrowLeft
import com.composables.icons.lucide.Bell
import com.composables.icons.lucide.Binary
import com.composables.icons.lucide.Zap
import com.composables.icons.lucide.BookOpen
import com.composables.icons.lucide.Bot
import com.composables.icons.lucide.Box
import com.composables.icons.lucide.Braces
import com.composables.icons.lucide.GitBranch
import com.composables.icons.lucide.Building
import com.composables.icons.lucide.Calendar
import com.composables.icons.lucide.Camera
import com.composables.icons.lucide.MessageSquare
import com.composables.icons.lucide.MessageCircle
import com.composables.icons.lucide.Check
import com.composables.icons.lucide.SquareCheck
import com.composables.icons.lucide.CheckCheck
import com.composables.icons.lucide.ChevronDown
import com.composables.icons.lucide.ChevronLeft
import com.composables.icons.lucide.ChevronRight
import com.composables.icons.lucide.ChevronsUpDown
import com.composables.icons.lucide.ChevronUp
import com.composables.icons.lucide.Circle
import com.composables.icons.lucide.ClipboardList
import com.composables.icons.lucide.Clock
import com.composables.icons.lucide.X
import com.composables.icons.lucide.CloudDownload
import com.composables.icons.lucide.Code
import com.composables.icons.lucide.GitCommitHorizontal
import com.composables.icons.lucide.Compass
import com.composables.icons.lucide.Container
import com.composables.icons.lucide.Copy
import com.composables.icons.lucide.Cpu
import com.composables.icons.lucide.Database
import com.composables.icons.lucide.Trash
import com.composables.icons.lucide.Diff
import com.composables.icons.lucide.Download
import com.composables.icons.lucide.HardDrive
import com.composables.icons.lucide.Pencil
import com.composables.icons.lucide.CircleAlert
import com.composables.icons.lucide.Expand
import com.composables.icons.lucide.ExternalLink
import com.composables.icons.lucide.Eye
import com.composables.icons.lucide.EyeOff
import com.composables.icons.lucide.FileText
import com.composables.icons.lucide.FileHeadphone
import com.composables.icons.lucide.FileCode
import com.composables.icons.lucide.FilePen
import com.composables.icons.lucide.FileImage
import com.composables.icons.lucide.FileSearch
import com.composables.icons.lucide.FilePlay
import com.composables.icons.lucide.Film
import com.composables.icons.lucide.Funnel
import com.composables.icons.lucide.FlaskConical
import com.composables.icons.lucide.FolderOpen
import com.composables.icons.lucide.GitFork
import com.composables.icons.lucide.Globe
import com.composables.icons.lucide.GripVertical
import com.composables.icons.lucide.Hash
import com.composables.icons.lucide.History
import com.composables.icons.lucide.Hourglass
import com.composables.icons.lucide.Image
import com.composables.icons.lucide.ImageOff
import com.composables.icons.lucide.ImagePlus
import com.composables.icons.lucide.Inbox
import com.composables.icons.lucide.Info
import com.composables.icons.lucide.Key
import com.composables.icons.lucide.Keyboard
import com.composables.icons.lucide.Languages
import com.composables.icons.lucide.Layers
import com.composables.icons.lucide.Link
import com.composables.icons.lucide.ListChecks
import com.composables.icons.lucide.Lock
import com.composables.icons.lucide.LogIn
import com.composables.icons.lucide.MapPin
import com.composables.icons.lucide.Maximize
import com.composables.icons.lucide.GitMerge
import com.composables.icons.lucide.Mic
import com.composables.icons.lucide.MicVocal
import com.composables.icons.lucide.Minimize
import com.composables.icons.lucide.Monitor
import com.composables.icons.lucide.Moon
import com.composables.icons.lucide.Ellipsis
import com.composables.icons.lucide.EllipsisVertical
import com.composables.icons.lucide.Music
import com.composables.icons.lucide.Network
import com.composables.icons.lucide.Notebook
import com.composables.icons.lucide.Palette
import com.composables.icons.lucide.Pause
import com.composables.icons.lucide.CirclePause
import com.composables.icons.lucide.Pin
import com.composables.icons.lucide.Package
import com.composables.icons.lucide.Play
import com.composables.icons.lucide.CirclePlay
import com.composables.icons.lucide.Plug
import com.composables.icons.lucide.Printer
import com.composables.icons.lucide.Puzzle
import com.composables.icons.lucide.RefreshCw
import com.composables.icons.lucide.RotateCcw
import com.composables.icons.lucide.Rocket
import com.composables.icons.lucide.Route
import com.composables.icons.lucide.Save
import com.composables.icons.lucide.ChartScatter
import com.composables.icons.lucide.Search
import com.composables.icons.lucide.Send
import com.composables.icons.lucide.Server
import com.composables.icons.lucide.Settings
import com.composables.icons.lucide.Shield
import com.composables.icons.lucide.Shrink
import com.composables.icons.lucide.SlidersHorizontal
import com.composables.icons.lucide.Sparkles
import com.composables.icons.lucide.LoaderCircle
import com.composables.icons.lucide.Star
import com.composables.icons.lucide.Square
import com.composables.icons.lucide.CircleCheckBig
import com.composables.icons.lucide.Sun
import com.composables.icons.lucide.ArrowLeftRight
import com.composables.icons.lucide.Tag
import com.composables.icons.lucide.CircleDot
import com.composables.icons.lucide.SquareTerminal
import com.composables.icons.lucide.Timer
import com.composables.icons.lucide.ListTodo
import com.composables.icons.lucide.Wrench
import com.composables.icons.lucide.Undo2
import com.composables.icons.lucide.Upload
import com.composables.icons.lucide.User
import com.composables.icons.lucide.UserRoundPlus
import com.composables.icons.lucide.Users
import com.composables.icons.lucide.Video
import com.composables.icons.lucide.TriangleAlert

/** Semantic icon slots shared by all four Easy Agent clients (tools/icons.py).
 *
 *  Compose's Lucide port exposes glyphs as extension properties on the
 *  `Lucide` object, so this table adapts the cross-client slot names to
 *  the library's own PascalCase properties. */
object AppIcons {
    val add: ImageVector get() = Lucide.Plus
    val apps: ImageVector get() = Lucide.LayoutGrid
    val arrow_up: ImageVector get() = Lucide.ArrowUp
    val asterisk: ImageVector get() = Lucide.Asterisk
    val attach: ImageVector get() = Lucide.Paperclip
    val audio: ImageVector get() = Lucide.AudioLines
    val back: ImageVector get() = Lucide.ArrowLeft
    val bell: ImageVector get() = Lucide.Bell
    val binary: ImageVector get() = Lucide.Binary
    val bolt: ImageVector get() = Lucide.Zap
    val book: ImageVector get() = Lucide.BookOpen
    val bot: ImageVector get() = Lucide.Bot
    val box: ImageVector get() = Lucide.Box
    val braces: ImageVector get() = Lucide.Braces
    val branch: ImageVector get() = Lucide.GitBranch
    val building: ImageVector get() = Lucide.Building
    val calendar: ImageVector get() = Lucide.Calendar
    val camera: ImageVector get() = Lucide.Camera
    val chat: ImageVector get() = Lucide.MessageSquare
    val chat_round: ImageVector get() = Lucide.MessageCircle
    val check: ImageVector get() = Lucide.Check
    val checked_square: ImageVector get() = Lucide.SquareCheck
    val checks: ImageVector get() = Lucide.CheckCheck
    val chevron_down: ImageVector get() = Lucide.ChevronDown
    val chevron_left: ImageVector get() = Lucide.ChevronLeft
    val chevron_right: ImageVector get() = Lucide.ChevronRight
    val chevron_select: ImageVector get() = Lucide.ChevronsUpDown
    val chevron_up: ImageVector get() = Lucide.ChevronUp
    val circle: ImageVector get() = Lucide.Circle
    val clipboard: ImageVector get() = Lucide.ClipboardList
    val clock: ImageVector get() = Lucide.Clock
    val close: ImageVector get() = Lucide.X
    val cloud_down: ImageVector get() = Lucide.CloudDownload
    val code: ImageVector get() = Lucide.Code
    val commit: ImageVector get() = Lucide.GitCommitHorizontal
    val compass: ImageVector get() = Lucide.Compass
    val container: ImageVector get() = Lucide.Container
    val copy: ImageVector get() = Lucide.Copy
    val cpu: ImageVector get() = Lucide.Cpu
    val database: ImageVector get() = Lucide.Database
    val delete: ImageVector get() = Lucide.Trash
    val diff: ImageVector get() = Lucide.Diff
    val download: ImageVector get() = Lucide.Download
    val drive: ImageVector get() = Lucide.HardDrive
    val edit: ImageVector get() = Lucide.Pencil
    val error: ImageVector get() = Lucide.CircleAlert
    val expand: ImageVector get() = Lucide.Expand
    val external: ImageVector get() = Lucide.ExternalLink
    val eye: ImageVector get() = Lucide.Eye
    val eye_off: ImageVector get() = Lucide.EyeOff
    val file: ImageVector get() = Lucide.FileText
    val file_audio: ImageVector get() = Lucide.FileHeadphone
    val file_code: ImageVector get() = Lucide.FileCode
    val file_edit: ImageVector get() = Lucide.FilePen
    val file_image: ImageVector get() = Lucide.FileImage
    val file_search: ImageVector get() = Lucide.FileSearch
    val file_video: ImageVector get() = Lucide.FilePlay
    val film: ImageVector get() = Lucide.Film
    val filter: ImageVector get() = Lucide.Funnel
    val flask: ImageVector get() = Lucide.FlaskConical
    val folder: ImageVector get() = Lucide.FolderOpen
    val fork: ImageVector get() = Lucide.GitFork
    val globe: ImageVector get() = Lucide.Globe
    val grip: ImageVector get() = Lucide.GripVertical
    val hash: ImageVector get() = Lucide.Hash
    val history: ImageVector get() = Lucide.History
    val hourglass: ImageVector get() = Lucide.Hourglass
    val image: ImageVector get() = Lucide.Image
    val image_off: ImageVector get() = Lucide.ImageOff
    val image_plus: ImageVector get() = Lucide.ImagePlus
    val inbox: ImageVector get() = Lucide.Inbox
    val info: ImageVector get() = Lucide.Info
    val key: ImageVector get() = Lucide.Key
    val keyboard: ImageVector get() = Lucide.Keyboard
    val language: ImageVector get() = Lucide.Languages
    val layers: ImageVector get() = Lucide.Layers
    val link: ImageVector get() = Lucide.Link
    val list: ImageVector get() = Lucide.ListChecks
    val lock: ImageVector get() = Lucide.Lock
    val login: ImageVector get() = Lucide.LogIn
    val map: ImageVector get() = Lucide.MapPin
    val maximize: ImageVector get() = Lucide.Maximize
    val merge: ImageVector get() = Lucide.GitMerge
    val mic: ImageVector get() = Lucide.Mic
    val mic_vocal: ImageVector get() = Lucide.MicVocal
    val minimize: ImageVector get() = Lucide.Minimize
    val monitor: ImageVector get() = Lucide.Monitor
    val moon: ImageVector get() = Lucide.Moon
    val more: ImageVector get() = Lucide.Ellipsis
    val more_vertical: ImageVector get() = Lucide.EllipsisVertical
    val music: ImageVector get() = Lucide.Music
    val network: ImageVector get() = Lucide.Network
    val notebook: ImageVector get() = Lucide.Notebook
    val palette: ImageVector get() = Lucide.Palette
    val pause: ImageVector get() = Lucide.Pause
    val pause_round: ImageVector get() = Lucide.CirclePause
    val pin: ImageVector get() = Lucide.Pin
    val pkg: ImageVector get() = Lucide.Package
    val play: ImageVector get() = Lucide.Play
    val play_round: ImageVector get() = Lucide.CirclePlay
    val plug: ImageVector get() = Lucide.Plug
    val printer: ImageVector get() = Lucide.Printer
    val puzzle: ImageVector get() = Lucide.Puzzle
    val refresh: ImageVector get() = Lucide.RefreshCw
    val revert: ImageVector get() = Lucide.RotateCcw
    val rocket: ImageVector get() = Lucide.Rocket
    val route: ImageVector get() = Lucide.Route
    val save: ImageVector get() = Lucide.Save
    val scatter: ImageVector get() = Lucide.ChartScatter
    val search: ImageVector get() = Lucide.Search
    val send: ImageVector get() = Lucide.Send
    val server: ImageVector get() = Lucide.Server
    val settings: ImageVector get() = Lucide.Settings
    val shield: ImageVector get() = Lucide.Shield
    val shrink: ImageVector get() = Lucide.Shrink
    val sliders: ImageVector get() = Lucide.SlidersHorizontal
    val sparkles: ImageVector get() = Lucide.Sparkles
    val spinner: ImageVector get() = Lucide.LoaderCircle
    val star: ImageVector get() = Lucide.Star
    val stop: ImageVector get() = Lucide.Square
    val success: ImageVector get() = Lucide.CircleCheckBig
    val sun: ImageVector get() = Lucide.Sun
    val swap: ImageVector get() = Lucide.ArrowLeftRight
    val tag: ImageVector get() = Lucide.Tag
    val target: ImageVector get() = Lucide.CircleDot
    val terminal: ImageVector get() = Lucide.SquareTerminal
    val timer: ImageVector get() = Lucide.Timer
    val todo: ImageVector get() = Lucide.ListTodo
    val tools: ImageVector get() = Lucide.Wrench
    val undo: ImageVector get() = Lucide.Undo2
    val upload: ImageVector get() = Lucide.Upload
    val user: ImageVector get() = Lucide.User
    val user_plus: ImageVector get() = Lucide.UserRoundPlus
    val users: ImageVector get() = Lucide.Users
    val video: ImageVector get() = Lucide.Video
    val warn: ImageVector get() = Lucide.TriangleAlert
}
